### PR TITLE
fix blocking call in event loop,  and add dev/test tooling

### LINKED ISSUE #7: Detected blocking call to import_module inside the event loop
### HA core version

2024.5.1

### Intergration version

0.3.24

### Device type and model

Air Conditioner 00000Q13 (8) and Air Conditioner 00000Q18 (44204)

### Used App

MSartHome and Home Assistant

### The description of problem

Registratore: homeassistant.util.loop
Fonte: util/loop.py:99
Prima occorrenza: 19:40:39 (4 occorrenze)
Ultima registrazione: 19:40:39

Detected blocking call to import_module inside the event loop by custom integration 'midea_ac_lan' at custom_components/midea_ac_lan/midea/devices/__init__.py, line 23: module = import_module(device_path, __package__) (offender: /config/custom_components/midea_ac_lan/midea/devices/__init__.py, line 23: module = import_module(device_path, __package__)), please create a bug report at https://github.com/georgezhao2010/midea_ac_lan/issues

### The logs

2024-05-03 19:40:19.859 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration midea_ac_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-03 19:40:39.334 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module inside the event loop by custom integration 'midea_ac_lan' at custom_components/midea_ac_lan/midea/devices/__init__.py, line 23: module = import_module(device_path, __package__) (offender: /config/custom_components/midea_ac_lan/midea/devices/__init__.py, line 23: module = import_module(device_path, __package__)), please create a bug report at https://github.com/georgezhao2010/midea_ac_lan/issues
2024-05-03 19:40:39.363 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module inside the event loop by custom integration 'midea_ac_lan' at custom_components/midea_ac_lan/midea/devices/__init__.py, line 23: module = import_module(device_path, __package__) (offender: /config/custom_components/midea_ac_lan/midea/devices/__init__.py, line 23: module = import_module(device_path, __package__)), please create a bug report at https://github.com/georgezhao2010/midea_ac_lan/issues
2024-05-03 19:40:39.374 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module inside the event loop by custom integration 'midea_ac_lan' at custom_components/midea_ac_lan/midea/devices/__init__.py, line 23: module = import_module(device_path, __package__) (offender: /config/custom_components/midea_ac_lan/midea/devices/__init__.py, line 23: module = import_module(device_path, __package__)), please create a bug report at https://github.com/georgezhao2010/midea_ac_lan/issues
2024-05-03 19:40:39.384 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module inside the event loop by custom integration 'midea_ac_lan' at custom_components/midea_ac_lan/midea/devices/__init__.py, line 23: module = import_module(device_path, __package__) (offender: /config/custom_components/midea_ac_lan/midea/devices/__init__.py, line 23: module = import_module(device_path, __package__)), please create a bug report at https://github.com/georgezhao2010/midea_ac_lan/issues

**Debug logging**:
[home-assistant_midea_ac_lan_2024-05-05T11-40-46.319Z.log](https://github.com/CyrielRct/midea_ac_lan/files/15212744/home-assistant_midea_ac_lan_2024-05-05T11-40-46.319Z.log)

### PR DESCRIPTION
**Pull request by attilaersek**
Hey!

First of all, I'd like to thank all your efforts you've put into resurrecting this project! I was worried that this integration is not maintained anymore, I hope you'll accept my very first contribution. 
I'm not a python developer (at all!) and I'm definitely not a HomeAssistant custom integration developer, so please triple test everything. I do my best to test my changes!

What's included:
- fix to #7 
- vscode devcontainer tooling to spin up a hass instance with the integration preinstalled (just go to settings and add the midea device you want for testing)

and a special commit that bumps versions and changes the component owner to you, @CyrielRct !

Let me know if you'd like to change something.

### CODE REVIEW

**Comment by Qianli-Ma** [comment]
Can you exclude the following folders for now?
- .devcontainer
- .vscode
I will update the .gitignore to ignore .vscode and such

**Comment by attilaersek** [comment]
> Can you exclude the following folders for now?
> - .devcontainer
> - .vscode
> I will update the .gitignore to ignore .vscode and such 

Yes, I can revert the developer tooling if you wish. Though it could simplify contributors life.

I'll push the change tomorrow!

Are you happy with the rest of the changes?

**Comment by Qianli-Ma** [comment]
> > Can you exclude the following folders for now?
> > 
> > * .devcontainer
> > * .vscode
> >   I will update the .gitignore to ignore .vscode and such
> 
> Yes, I can revert the developer tooling if you wish. Though it could simplify contributors life.
> 
> I'll push the change tomorrow!
> 
> Are you happy with the rest of the changes?

True, but some people might prefer their own environment though. Everything else looks good

**Review by Qianli-Ma — APPROVED** [review]

**Comment by Qianli-Ma** [comment]
> > Can you exclude the following folders for now?
> > 
> > * .devcontainer
> > * .vscode
> >   I will update the .gitignore to ignore .vscode and such
> 
> Yes, I can revert the developer tooling if you wish. Though it could simplify contributors life.
> 
> I'll push the change tomorrow!
> 
> Are you happy with the rest of the changes?

On second thought, I believe that you are correct. Let's keep the developer tooling.

**Review by Qianli-Ma — APPROVED** [review]

**Comment by attilaersek** [comment]
> > > Can you exclude the following folders for now?
> > > 
> > > * .devcontainer
> > > * .vscode
> > >   I will update the .gitignore to ignore .vscode and such
> > 
> > Yes, I can revert the developer tooling if you wish. Though it could simplify contributors life.
> > 
> > I'll push the change tomorrow!
> > 
> > Are you happy with the rest of the changes?
> 
> On second thought, I believe that you are correct. Let's keep the developer tooling. 

Appreciate your quick response and openness! Let me know if I can help somehow!

**Pull request merged**
